CREATE TABLE PLAYER (
  PLAYER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  PLAYER_NAME VARCHAR(250) NOT NULL,
  PLAYER_COLOUR VARCHAR(250) NOT NULL,
  PLAYER_BALANCE BIGINT NOT NULL,
  PLAYER_BOARD_POSITION BIGINT NOT NULL
);